# Generated by Django 3.2.25 on 2024-05-15 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_orm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
