# Generated by Django 3.2.25 on 2024-05-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orm', '0006_book_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='books',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='actor',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='movies', to='app_orm.Actor'),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
